podTemplate(
    inheritFrom: "maven", 
    label: "myJenkins", 
    cloud: "openshift", 
    volumes: [
        persistentVolumeClaim(claimName: "m2repo", mountPath: "/home/jenkins/.m2/")
    ]) {

    node("myJenkins") {

        @Library('github.com/redhat-helloworld-msa/jenkins-library@master') _
        
        stage ('SCM checkout'){
            echo 'Checking out git repository'
            checkout scm
        }
    	
    	dir('hellotest'){
    	echo 'Using directory hellotest'
	        stage ('Maven build'){
	            echo 'Building project'
	            sh "mvn package"
	        }
	    
	        stage ('DEV - Image build'){
	            echo 'Building docker image and deploying to Dev'
	            buildApp('hellotest-dev', "hellotest")
	            echo "This is the build number: ${env.BUILD_NUMBER}"
	        }
	    
	        stage ('PRD - Promote image'){
	            echo 'Deploying to production'
	            promoteImage('hellotest-dev', 'hellotest', 'hellotest', env.BUILD_NUMBER)
	        }
	
	        stage ('PRD - Canary Deploy'){
	            echo 'Performing a canary deployment'
	            canaryDeploy('hellotest', 'hellotest', env.BUILD_NUMBER)
	        }
	   }

    }
} 
